# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160907_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_comment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.Comment', verbose_name='回复哪个评论'),
        ),
    ]
