# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-18 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_to_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='to_comment_id',
            new_name='to_comment',
        ),
    ]
