# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 11:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activate',
            options={'verbose_name': '激活码', 'verbose_name_plural': '激活码'},
        ),
    ]
