# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_userprofile_portrait'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '用户中心', 'verbose_name_plural': '用户中心'},
        ),
    ]
